language: r
dist: trusty
sudo: false

branches:
  only:
    - master

cache:
  packages: yes
  directories:
    - $HOME/bin

install:
  - Rscript -e 'install.packages(c("lubridate", "dplyr", "reshape2", "data.table", "data.table", "data.table", "car", "dplyr", "data.table", "data.table", "plotly", "tidyverse", "ggplot2", "plotly", "tidyverse", "sqldf", "blogdown"))'

before_script:
  - "Rscript -e 'blogdown::install_hugo()'"

script:
  - "Rscript -e 'blogdown::build_site()'"

deploy:
  local_dir: public
  provider: pages
  repo: tomis9/tomis9.github.io 
  target_branch: master 
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  email: tomis9@buziaczek.pl
  name: tomis9
  on:
    branch: master
