language: minimal
cache: packages
dist: xenial
sudo: false

branches:
  only:
    - master

before_install:
  - docker pull tomis9/cookbook:0.10
  - docker run -v /home/travis/build/greysweater42/cookbook:/cookbook tomis9/cookbook:0.10

deploy:
  local_dir: public
  provider: pages
  repo: greysweater42/greysweater42.github.io 
  target_branch: master 
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  email: greysweater42@gmail.com
  name: greysweater42
  on:
    branch: master
