language: minimal
cache: packages
dist: xenial
sudo: false

branches:
  only:
    - master

before_install:
  - docker pull tomis9/cookbook:0.3
  - docker run -v /home/travis/build/tomis9/cookbook/hugo:/cookbook/hugo tomis9/cookbook:0.3




deploy:
  local_dir: hugo/public
  provider: pages
  repo: tomis9/tomis9.github.io 
  target_branch: master 
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  email: tomis9@buziaczek.pl
  name: tomis9
  on:
    branch: master
