baseURL                    = "tomis9.com"
builddrafts                = false
canonifyurls               = true
contentdir                 = "content"
layoutdir                  = "layouts"
publishdir                 = "public"

theme                      = "random_forest"
title                      = "tomis9's cookbook"

[taxonomies]
  tag                      = "tags"
  series                   = "series"
  category                 = "categories"


[menu]

  [[menu.main]]
    name                   = "Python"
    weight                 = 10
    identifier             = "python"
    url                    = "categories/python/" 
  [[menu.main]]
    name                   = "R"
    weight                 = 20
    identifier             = "R"
    url                    = "categories/r/"  

  [[menu.main]]
    name                   = "Data engineering"
    weight                 = 30
    identifier             = "data-engineering"
    url                    = "categories/data-engineering/"  
 
  [[menu.main]]
    name                   = "Machine learning"
    weight                 = 35
    identifier             = "machine-learning"
    url                    = "categories/machine-learning/"  

  [[menu.main]]
    name                   = "DevOps"
    weight                 = 40
    identifier             = "DevOps"
    url                    = "categories/devops/"  

  [[menu.main]]
    name                   = "Projects"
    weight                 = 50
    identifier             = "projects"
    url                    = "categories/projects/"  

  [[menu.main]]
    name                   = "scratchpad"
    weight                 = 60
    identifier             = "scratchpad"
    url                    = "categories/scratchpad/"  

[params]
  title = "tomis9's cookbook"
  description              = "data science tutorials and snippets prepared by tomis9"
  # faviconfile              = "favicon.ico"
