baseurl         = "https://tomis9.github.io"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
title           = "tomis9's cookbook"
#SectionPagesMenu = "main"

[params]
  title       = "tomis9's cookbook"
  # subtitle    = "or my personal programming tutorials and snippets"
  subtitle = "WIP: moving to HUGO"
  cover       = "home.jpg"
  description = "programming tutorials and snippets prepared by tomis9"
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  githubName = "tomis9"

  logo = ""
  orgName = "tomis9' cookbook"
  orgWebsite = "tomis.github.io"
  orgDescription = "programming tutorials and snippets prepared by tomis9"

  author = "tomis9"
  authorAvatar = "avatar.png"
  authorLocation = "Warsaw, Poland"
  authorWebsite = "https://tomis9.github.io"
  authorDescription = "A regular everyday data scientist who's trying to manifest his hipsterity by coding in vim"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "caspertwo"

[permalinks]
  post = "/:slug/"

# weight wskazuje na kolejność

[[menu.main]]
  name = "home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Python"
  url = "/categories/python/"
  weight = 100

[[menu.main]]
  name = "R"
  url = "/categories/R/"
  weight = 99

[[menu.main]]
  name = "DevOps"
  url = "/categories/DevOps/"
  weight = 98

[[menu.main]]
  name = "Big Data"
  url = "https://google.com/"
  weight = 97

[[menu.main]]
  name = "Data engineering"
  url = "https://google.com/"
  weight = 96

