baseURL = "https://greysweater42.github.io"
# baseURL                    = ""
builddrafts                = false
canonifyurls               = true
contentdir                 = "content"
layoutdir                  = "layouts"
publishdir                 = "public"
preserveTaxonomyNames = true
theme                      = "random_forest"
title                      = "greaysweater42's cookbook"

[taxonomies]
  tag                      = "tags"
  series                   = "series"
  category                 = "categories"


[menu]

  [[menu.main]]
    name                   = "Python"
    weight                 = 10
    identifier             = "Python"
    url                    = "categories/python/" 
  [[menu.main]]
    name                   = "R"
    weight                 = 20
    identifier             = "R"
    url                    = "categories/r/"  

  [[menu.main]]
    name                   = "Machine learning"
    weight                 = 30
    identifier             = "Machine learning"
    url                    = "categories/machine-learning/"  

  [[menu.main]]
    name                   = "Data engineering"
    weight                 = 40
    identifier             = "Data engineering"
    url                    = "categories/data-engineering/"  

  [[menu.main]]
    name                   = "DevOps"
    weight                 = 50
    identifier             = "DevOps"
    url                    = "categories/devops/"  

  [[menu.main]]
    name                   = "Projects"
    weight                 = 70
    identifier             = "Projects"
    url                    = "categories/projects/"  

  [[menu.main]]
    name                   = "scratchpad"
    weight                 = 80
    identifier             = "scratchpad"
    url                    = "categories/scratchpad/"  

[params]
  header = "grey <span style='position: relative; top: -10px;'> sweater</span> 42's</br>cookbook"
  title = "greysweater42's cookbook"
  description              = "data science tutorials and snippets prepared by greysweater42"
  # faviconfile              = "favicon.ico"

# for raw html parsing
[markup]
  [markup.goldmark.renderer]
    unsafe=true
