baseurl         = "https://tomis9.github.io"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "tomis9's cookbook"
  subtitle    = "or my personal programming tutorials and snippets"

  cover       = "header.jpeg"
  description = "to jest description, ciekawe gdzie ono sie pojawia"
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  githubName = "tomis9"

  logo = ""
  orgName = "EM"
  orgWebsite = "https://www.telematika.org"
  orgDescription = "Here is a description placeholder for your org"

  author = "EM"
  authorAvatar = "img/ghost-icon.png"
  authorLocation = "Warsaw, Poland"
  authorWebsite = "https://tomis9.github.io"
  authorDescription = "Describe yourself.."

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

# weight wskazuje na kolejność

[[menu.main]]
  name = "home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Python"
  url = "/tags/python/"
  weight = 100

[[menu.main]]
  name = "R"
  url = "/R/"
  weight = 99

[[menu.main]]
  name = "DevOps"
  url = "/tags/DevOps/"
  weight = 98

[[menu.main]]
  name = "Big Data"
  url = "https://google.com/"
  weight = 97

[[menu.main]]
  name = "Data engineering"
  url = "https://google.com/"
  weight = 96

