name: build
on: push

jobs:
  build:
    name: build and deploy to gihub pages
    runs-on: ubuntu-latest
    container:
        image: ghcr.io/greysweater42/cookbook:latest
        credentials:
          username: greysweater42
          password: ${{ secrets.COOKBOOK_TOKEN }}
    steps:
    - name: build and push to github pages
      env:
        COOKBOOK_TOKEN: ${{ secrets.COOKBOOK_TOKEN }}
      run: |
          git config --global user.email "auto@auto.com"
          git config --global user.name "auto"
          git clone https://github.com/greysweater42/cookbook
          cd cookbook
          Rscript -e "blogdown::build_site()"
          git clone https://${COOKBOOK_TOKEN}@github.com/greysweater42/greysweater42.github.io
          cd greysweater42.github.io
          rm -rf *
          cp -r ../public/* .
          git add .
          git commit -m "commit"
          git push

